import logging
from typing import List, Dict
import time
import httpx
import aiosqlite
import uuid
from ..providers.cognee import CogneeProvider
from ..providers.relational import SQLiteRelationalProvider
from ..core.lsa import LSAEngine
from ..core.config import settings

logger = logging.getLogger(__name__)

class ConsolidationEngine:
    """
    Background service for knowledge synthesis and pruning.
    Implements the 'Self-Cleaning' logic of the Evolutionary Knowledge Hub.
    """
    
    def __init__(self, cognee: CogneeProvider, rdbms: SQLiteRelationalProvider, lsa: LSAEngine):
        self.cognee = cognee
        self.rdbms = rdbms
        self.lsa = lsa

    async def _llm_synthesize(self, cluster: List[str]) -> str:
        """Calls the configured LLM to synthesize a cluster of facts."""
        if not settings.llm_provider_url:
            return f"Consolidated Wisdom of {len(cluster)} facts. Generated by Thalamus Heuristic."
        
        base_url = settings.llm_provider_url.rstrip("/")
        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                # 1. Check if model exists
                tags_resp = await client.get(f"{base_url}/api/tags")
                tags_resp.raise_for_status()
                models = [m.get("name") for m in tags_resp.json().get("models", [])]
                
                if settings.llm_model_name not in models:
                    if settings.llm_auto_pull:
                        logger.info(f"[Thalamus] Model '{settings.llm_model_name}' missing. Attempting auto-pull...")
                        pull_resp = await client.post(f"{base_url}/api/pull", json={"name": settings.llm_model_name}, timeout=300.0)
                        pull_resp.raise_for_status()
                        logger.info(f"[Thalamus] Successfully pulled model '{settings.llm_model_name}'.")
                    else:
                        logger.error(f"[Thalamus] Model '{settings.llm_model_name}' missing and auto-pull is disabled.")
                        return f"Consolidated Wisdom of {len(cluster)} facts. (Model Missing)"

                # 2. Generate synthesis
                prompt = f"Synthesize these related facts into a single, concise 'Wisdom Node' that preserves the final state:\n" + "\n".join(cluster)
                resp = await client.post(f"{base_url}/api/generate", json={
                    "model": settings.llm_model_name,
                    "prompt": prompt,
                    "stream": False
                })
                resp.raise_for_status()
                return resp.json().get("response", "").strip()
        except Exception as e:
            logger.error(f"[Thalamus] LLM Synthesis error: {e}")
            return f"Consolidated Wisdom of {len(cluster)} facts. (Synthesis Failed)"

    async def run_consolidation_pass(self, agent_id: str):
        """
        Scans the graph for conflicting or redundant nodes and merges them.
        """
        logger.info(f"[Thalamus] Starting consolidation pass for agent: {agent_id}")
        
        # 1. Fetch active nodes
        reputations = await self.rdbms.get_fact_reputations(agent_id)
        active_nodes = [node_id for node_id, rep in reputations.items() if rep["status"] == "ACTIVE"]
        
        if len(active_nodes) < settings.consolidation_cluster_size:
            logger.info(f"[Thalamus] Not enough active nodes (<{settings.consolidation_cluster_size}) to warrant consolidation.")
            return 0
            
        # 2. Simulate Semantic Clustering
        cluster = sorted(active_nodes, key=lambda n: reputations[n]["success"], reverse=True)[:settings.consolidation_cluster_size]
        
        # 3. LSA Pattern Detection & Synthesis
        abstraction = await self.lsa.detect_patterns(agent_id, cluster)
        if abstraction:
            abstraction.source_refs = cluster
            await self.lsa.create_or_update_abstraction(abstraction)
            new_node_id = abstraction.id
            summary = abstraction.description
            
            # We also ingest a summary text back to Cognee for searchability
            await self.cognee.add_text(f"Abstraction: {abstraction.name}\n{abstraction.description}", dataset_name=f"doc_seed_{agent_id}")
        else:
            # Fallback to simple synthesis if LSA fails
            combined_wisdom = await self._llm_synthesize(cluster)
            new_node_id = f"wisdom_{uuid.uuid4().hex[:8]}"
            await self.cognee.add_text(combined_wisdom, dataset_name=f"doc_seed_{agent_id}")
            summary = combined_wisdom

        # 4. Tombstone old nodes (Temporal Provenance)
        now = int(time.time())
        async with aiosqlite.connect(self.rdbms.db_path) as db:
            # Add metadata for the new Wisdom/Abstraction node in fact_reputation
            await db.execute("""
                INSERT INTO fact_reputation (node_id, agent_id, success_count, last_verified_at, status, is_verified, abstraction_id)
                VALUES (?, ?, ?, ?, 'ACTIVE', 1, ?)
            """, (new_node_id, agent_id, len(cluster), now, new_node_id if abstraction else None))
            
            # Tombstone old nodes and link them to the abstraction
            for old_node in cluster:
                await db.execute("""
                    UPDATE fact_reputation 
                    SET status = 'CONSOLIDATED', abstraction_id = ? 
                    WHERE node_id = ? AND agent_id = ?
                """, (new_node_id if abstraction else None, old_node, agent_id))
            
            # Record edges in consolidation_log
            await db.execute("""
                INSERT INTO consolidation_log (agent_id, timestamp, nodes_merged_count, new_node_id, summary)
                VALUES (?, ?, ?, ?, ?)
            """, (agent_id, now, len(cluster), new_node_id, f"LSA Consolidated: {summary[:100]}..."))
            
            await db.commit()
            
        logger.info(f"[Thalamus] Consolidated {len(cluster)} nodes into {new_node_id} (LSA: {bool(abstraction)})")
        return len(cluster)

    async def decay_stale_knowledge(self, agent_id: str, days_threshold: int = 30):
        """
        Prunes knowledge that hasn't been accessed or reinforced for a long time.
        """
        # Logic to scan SQLite fact_reputation for last_verified_at < threshold
        pass
